---
- name: Install vim
  apt:
    name: vim
    state: latest

- name: Create .vim config directory
  file:
   path: "{{ vim_config_root }}/.vim"
   state: directory

- name: Vundle | Clone repository
  git:
    dest: "{{ vim_config_root }}/.vim/bundle/Vundle.vim"
    repo: 'https://github.com/VundleVim/Vundle.vim.git'

- name: Upload vim configuration
  copy:
    dest: "{{ vim_config_root }}/.vimrc"
    src: .vimrc
