---
- name: Install vim
  apt:
    name: vim
    state: latest

- name: Create .vim config directory
  file:
   path: "{{ vim_config_root }}/.vim"
   state: directory

- name: pathogen.vim | Create autoload directory to install pathogen.vim in
  file:
    path: "{{ vim_config_root }}/.vim/autoload"
    state: directory

- name: pathogen.vim | Install
  get_url:
    dest: "{{ vim_config_root }}/.vim/autoload/pathogen.vim"
    mode: 0644
    url: 'https://tpo.pe/pathogen.vim'

- name: fugitive.vim | Clone repository
  git:
    dest: "{{ vim_config_root }}/.vim/bundle/vim-fugitive"
    repo: 'https://github.com/tpope/vim-fugitive.git'

- name: fugitive.vim | Install helptags
  command: "vim -u NONE -c 'helptags {{ vim_config_root }}/.vim/bundle/vim-fugitive/doc' -c q"
  register: fugitive_helptags
  changed_when: 'fugitive_helptags.stdout != ""'

- name: Upload vim configuration
  copy:
    dest: "{{ vim_config_root }}/.vimrc"
    src: .vimrc
