---
- name: Install vim
  become: true
  apt:
    name: vim
    state: latest

- name: Create .vim config directory
  file:
   path: "{{ vim_config_root }}/.vim"
   state: directory

- name: Vundle | Clone repository
  git:
    dest: "{{ vim_config_root }}/.vim/bundle/Vundle.vim"
    repo: 'https://github.com/VundleVim/Vundle.vim.git'

- name: YouCompleteMe | Install dependencies
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - cmake

- name: Upload vim configuration
  copy:
    dest: "{{ vim_config_root }}/.vimrc"
    src: .vimrc

- name: Upload syntax specific configuration
  copy:
    dest: "{{ vim_config_root }}/.vim/"
    src: ftplugin

- name: Install plugins
  command: vim +PluginInstall +qall

- name: YouCompleteMe | Complete install
  command: "{{ vim_config_root }}/.vim/bundle/YouCompleteMe/install.py"
